project:
  type: website

website:
  title: "ACEDdata"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: DataFiles.qmd
        text: Data
      - href: ACEDcodebook.qmd
        text: "Code Book"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



