project:
  type: website

website:
  title: "ACED data"
  navbar:
    logo: img/ACEDlogo.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: DataFiles.qmd
        text: Data
      - href: ACEDcodebook.qmd
        text: "Code Book"
      - href: BayesNet.qmd
        text: "Bayes Nets"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



